services:
  mysql:
    container_name: mysql-container
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: repair
    ports:
      - 3306:3306
volumes:
  todo-mysql-data: